### PR TITLE
allow SDK versions to be configurable

### PR DESCRIPTION
**Pull request by wlan0**
This PR allows the versions of the following SDK versions to be configurable

- awscli
- mc
- minio-dotnet
- minio-go
- minio-java
- minio-js
- minio-py

This is required for gateway tests, since there was a mismatch between the latest version and the lastest available version from this URL `https://dl.minio.io/client/mc/release/linux-amd64/mc.${MC_VERSION}`

By explicitly allowing the version to be set, we can avoid the above issue. 

The existing behavior is maintained if the versions are not explicitly set.

### CODE REVIEW

**Comment by wlan0** [comment]
@nitisht 
I originally did this because few of the SDKs did not work while running gateway tests - `minio-java` would not finish executing. `mc` build was looking for a non-existent version. This change parametrizes the versions. Other than allowing me to pin the versions to get over above hurdles, this will also enable testing multiple versions of the SDK for a release of minio. 

> @wlan0 initial vision while developing mint was that if sdk has an issue we fix the sdk and make a release instead of reverting to a working version. So we did not make the version configurable.

> IMHO this goes against that initial philosophy. Is there any specific reason to do this ?

I didn’t know about the philosophy. I understand your concern. Essentially, this change enables users to choose a version if they wanted to, and gives them the keys to revert to working version if they so chose, instead of fixing a broken SDK.

Given your concerns,  and given that mint tests seem to be going smoothly now, I dont think this PR is needed anymore. I’m happy to close this, any thoughts @nitisht @vadmeste?

**Comment by harshavardhana** [comment]
We should discuss this again once @wlan0 @nitisht  with @abperiasamy - if there are benefits in this approach we can keep the PR for now.

**Comment by vadmeste** [comment]
This PR doesn't change the old behavior by default, it only does that when we set SDK_VERSION in the environment. I would say this can be useful for us for debugging.

**Comment by nitisht** [comment]
Moved to blocked, pending discussion with @abperiasamy .

**Pull request closed without merging**
