### PR TITLE
Add SELFSIGNED_CERT env variable to trust server's tls cert

### PR DESCRIPTION
**Pull request by vadmeste**
This commit makes it easier for developers to test mint using their
local Minio server deployment loaded with a self signed certificate.

### CODE REVIEW

**Comment by nitisht** [comment]
@vadmeste can you PTAL at shellcheck failures

**Comment by vadmeste** [comment]
@nitisht fixed

**Comment by vadmeste** [comment]
ping @nitisht

**Comment by nitisht** [comment]
Travis is failing still @vadmeste

**Comment by vadmeste** [comment]
Travis still failing because Github is blocking access to api.github.com, we need to discuss this https://github.com/minio/mint/issues/294

**Pull request merged**
